// <auto-generated />
using System;
using FlowForge.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlowForge.Persistence.Migrations
{
    [DbContext(typeof(FlowForgeAPIDbContext))]
    partial class FlowForgeAPIDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlowForge.Domain.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("FlowForge.Domain.Entities.DeliveryAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseBodySnippet")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StatusCode")
                        .HasColumnType("text");

                    b.Property<Guid?>("WebhookDeliveryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WebhookDeliveryId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WebhookDeliveryId");

                    b.HasIndex("WebhookDeliveryId1");

                    b.ToTable("DeliveryAttempt");
                });

            modelBuilder.Entity("FlowForge.Domain.Entities.Membership", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TenantId", "UserId");

                    b.ToTable("Membership");
                });

            modelBuilder.Entity("FlowForge.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("FlowForge.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FlowForge.Domain.Entities.WebhookDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FinalResultAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EndpointId");

                    b.HasIndex("TenantId");

                    b.ToTable("WebhookDeliveries");
                });

            modelBuilder.Entity("FlowForge.Domain.Entities.WebhookEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("WebhookEndpoints");
                });

            modelBuilder.Entity("FlowForge.Domain.Entities.ApiKey", b =>
                {
                    b.HasOne("FlowForge.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FlowForge.Domain.ValueObjects.HashedApiKey", "Key", b1 =>
                        {
                            b1.Property<Guid>("ApiKeyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("ApiKeyId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("ApiKeys");

                            b1.WithOwner()
                                .HasForeignKey("ApiKeyId");
                        });

                    b.Navigation("Key")
                        .IsRequired();
                });

            modelBuilder.Entity("FlowForge.Domain.Entities.DeliveryAttempt", b =>
                {
                    b.HasOne("FlowForge.Domain.Entities.WebhookDelivery", null)
                        .WithMany()
                        .HasForeignKey("WebhookDeliveryId");

                    b.HasOne("FlowForge.Domain.Entities.WebhookDelivery", null)
                        .WithMany("Attempts")
                        .HasForeignKey("WebhookDeliveryId1");
                });

            modelBuilder.Entity("FlowForge.Domain.Entities.Membership", b =>
                {
                    b.HasOne("FlowForge.Domain.Entities.Tenant", null)
                        .WithMany("Memberships")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlowForge.Domain.Entities.Tenant", b =>
                {
                    b.OwnsOne("FlowForge.Domain.ValueObjects.PlanLimits", "PlanLimits", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.Property<int>("MaxEndpointsAllowed")
                                .HasColumnType("integer");

                            b1.Property<int>("MaxEventsPerMinute")
                                .HasColumnType("integer");

                            b1.Property<int>("MaxMembersAllowed")
                                .HasColumnType("integer");

                            b1.HasKey("TenantId");

                            b1.ToTable("Tenants");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.Navigation("PlanLimits")
                        .IsRequired();
                });

            modelBuilder.Entity("FlowForge.Domain.Entities.User", b =>
                {
                    b.OwnsOne("FlowForge.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("FlowForge.Domain.ValueObjects.ExternalIdentityId", "ExternalIdentityId", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ExternalId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("UserId");

                            b1.HasIndex("ExternalId")
                                .IsUnique();

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("ExternalIdentityId")
                        .IsRequired();
                });

            modelBuilder.Entity("FlowForge.Domain.Entities.WebhookDelivery", b =>
                {
                    b.HasOne("FlowForge.Domain.Entities.WebhookEndpoint", null)
                        .WithMany()
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowForge.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FlowForge.Domain.ValueObjects.EventType", "EventType", b1 =>
                        {
                            b1.Property<Guid>("WebhookDeliveryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("WebhookDeliveryId");

                            b1.ToTable("WebhookDeliveries");

                            b1.WithOwner()
                                .HasForeignKey("WebhookDeliveryId");
                        });

                    b.OwnsOne("FlowForge.Domain.ValueObjects.RetryPolicy", "RetryPolicy", b1 =>
                        {
                            b1.Property<Guid>("WebhookDeliveryId")
                                .HasColumnType("uuid");

                            b1.Property<TimeSpan>("InitialDelay")
                                .HasColumnType("interval");

                            b1.Property<int>("MaxAttempts")
                                .HasColumnType("integer");

                            b1.Property<TimeSpan>("MaxDelay")
                                .HasColumnType("interval");

                            b1.Property<string>("Strategy")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<TimeSpan>("TimeOut")
                                .HasColumnType("interval");

                            b1.HasKey("WebhookDeliveryId");

                            b1.ToTable("WebhookDeliveries");

                            b1.WithOwner()
                                .HasForeignKey("WebhookDeliveryId");
                        });

                    b.OwnsOne("FlowForge.Domain.ValueObjects.IdempotencyKey", "IdempotencyKey", b1 =>
                        {
                            b1.Property<Guid>("WebhookDeliveryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)");

                            b1.HasKey("WebhookDeliveryId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("WebhookDeliveries");

                            b1.WithOwner()
                                .HasForeignKey("WebhookDeliveryId");
                        });

                    b.Navigation("EventType")
                        .IsRequired();

                    b.Navigation("IdempotencyKey")
                        .IsRequired();

                    b.Navigation("RetryPolicy")
                        .IsRequired();
                });

            modelBuilder.Entity("FlowForge.Domain.Entities.WebhookEndpoint", b =>
                {
                    b.HasOne("FlowForge.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FlowForge.Domain.ValueObjects.RetryPolicy", "RetryPolicy", b1 =>
                        {
                            b1.Property<Guid>("WebhookEndpointId")
                                .HasColumnType("uuid");

                            b1.Property<TimeSpan>("InitialDelay")
                                .HasColumnType("interval");

                            b1.Property<int>("MaxAttempts")
                                .HasColumnType("integer");

                            b1.Property<TimeSpan>("MaxDelay")
                                .HasColumnType("interval");

                            b1.Property<string>("Strategy")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<TimeSpan>("TimeOut")
                                .HasColumnType("interval");

                            b1.HasKey("WebhookEndpointId");

                            b1.ToTable("WebhookEndpoints");

                            b1.WithOwner()
                                .HasForeignKey("WebhookEndpointId");
                        });

                    b.OwnsMany("FlowForge.Domain.ValueObjects.EventType", "SubscribedEventTypes", b1 =>
                        {
                            b1.Property<Guid>("WebhookEndpointId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("WebhookEndpointId", "Id");

                            b1.ToTable("WebhookEndpoints_SubscribedEventTypes");

                            b1.WithOwner()
                                .HasForeignKey("WebhookEndpointId");
                        });

                    b.OwnsOne("FlowForge.Domain.ValueObjects.EndpointName", "Name", b1 =>
                        {
                            b1.Property<Guid>("WebhookEndpointId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("WebhookEndpointId");

                            b1.ToTable("WebhookEndpoints");

                            b1.WithOwner()
                                .HasForeignKey("WebhookEndpointId");
                        });

                    b.OwnsOne("FlowForge.Domain.ValueObjects.SigningSecret", "SigningSecret", b1 =>
                        {
                            b1.Property<Guid>("WebhookEndpointId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)");

                            b1.HasKey("WebhookEndpointId");

                            b1.ToTable("WebhookEndpoints");

                            b1.WithOwner()
                                .HasForeignKey("WebhookEndpointId");
                        });

                    b.OwnsOne("FlowForge.Domain.ValueObjects.Url", "TargetUrl", b1 =>
                        {
                            b1.Property<Guid>("WebhookEndpointId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)");

                            b1.HasKey("WebhookEndpointId");

                            b1.ToTable("WebhookEndpoints");

                            b1.WithOwner()
                                .HasForeignKey("WebhookEndpointId");
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("RetryPolicy")
                        .IsRequired();

                    b.Navigation("SigningSecret")
                        .IsRequired();

                    b.Navigation("SubscribedEventTypes");

                    b.Navigation("TargetUrl")
                        .IsRequired();
                });

            modelBuilder.Entity("FlowForge.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("FlowForge.Domain.Entities.WebhookDelivery", b =>
                {
                    b.Navigation("Attempts");
                });
#pragma warning restore 612, 618
        }
    }
}
